= DevineLaCarte
:author: Amir KATSIEV
:docdate: 2022-10-11
:asciidoctor-version:1.1
:description: Projet pédagogique d'initiation à Kotlin
:icons: font
:listing-caption: Listing
:toc-title: Table des matières
:toc: left
:toclevels: 4

//:source-highlighter: coderay

== Thème

Développer une logique de jeu mettant en oeuvre de la conception objet et des tests unitaires.

Jeu en mode console. Un début d'implémentation est proposé (`MainPlayConsole.kt` en interaction en mode console/terminal)

=== Prérequis

Niveau : Deuxième année de BTS SIO SLAM

* Bases de la programmation,
* IntelliJ et kotlin opérationnels sur votre machine de dev
* Avoir fait des premiers pas avec Kotlin (exercices d'initiation)
* Avoir eu une première introduction à la notion de Test Unitaire, distinction entre *_expected value_* et *_actual value_*, dans une approche prédictive. En particulier avoir réalisé avec succès l'exercice https://ldv-melun.github.io/sio-slam/sio-component/exercice-premiers-pas-POO-TU-Kotlin.html[Faites vos comptes]


== Objectif

* Conception et mise au point d'une logique applicative avec Kotlin et JUnit

* Structure de données, recherche d'un élément dans une liste

* Analyse des actions du joueur (fonction du nombre de cartes, aides à la décision)


== Premiers Version du Project
[plantuml]
-----
@startuml
start
:Demmarage Jeu;

  :Saisir Paquet Cartes 32/52;

:Instanciation du jeu;

:Entrez la couleur/nom de carte;
:Carte existe?;
    if  (carte match) then (true)
      :Vous avez trouvé la carte;
      end
    else
      :Pas la bonne carte;
end
   endif
@enduml
-----


== Challenge-1 : Prise en main et tests unitaires

Le premier challenge consisté à définir une logique aux 4 tests suivants

* `fabriqueDe52Cartes()`
* `fabriqueDe32Cartes()`
* `testGetCartes()`
* `compareCartesDeCouleurDifferenteMaisDeMemeValeur()`

<1> Fabrications de paquet de cartes 32 ou 52 nous avons utilisé la méthode  `createJeu32Cartes()` ou `createJeu52Cartes()`
<2> Pour le `testGetCartes()` nous avons cree un Paquet et avec la methode `paquet.cartes.size` nous avons pris la taille du paquet
pour ensuite pouvoir tester à l'aide de assertEquals que nous avons bien 32  éléments dans le paquet
<3> Pour le test `compareCartesDeCouleurDifferenteMaisDeMemeValeur()` nous avons cree 2 cartes qu'on a comparé avec la méthode `compareTo`



[source, kotlin]
----
    @Test
    fun fabriqueDe32Cartes() {
    val jeu2Carte32 = createJeu32Cartes()
    assertEquals(32,jeu2Carte32.size)
        // TODO test fabriqueDe32Cartes à implémenter
    }

    @Test
    fun fabriqueDe52Cartes() {
        val jeu2Carte52 = createJeu52Cartes()
        assertEquals(52,jeu2Carte52.size)
        // TODO test fabriqueDe52Cartes à implémenter :

    }

----
== Challenge-2 : Jouer avec le jeu

Représentation de l’algorithme initial de la fonction main
[plantuml]
-----
@startuml
start
:Demmarage Jeu;

  :Saisir Paquet Cartes 32/52;

:Instanciation du jeu;

:Entrez la couleur/nom de carte;
:Carte existe?;
    if  (carte match) then (true)
      :Vous avez trouvé la carte;
      end
    else
      :Pas la bonne carte;
end
   endif
@enduml
-----
[plantuml]
-----
@startuml
start
:Demmarage Jeu;

repeat
repeat
  :Saisir Paquet Cartes 32/52;
repeat while (Paquet existe?) is (no) not (yes)
:Instanciation du jeu;
repeat
:Entrez la couleur/nom de carte;
  repeat while (Carte existe ?) is (no) not (yes)
    if  (carte match) then (true)
      :Vous avez trouvé la carte;
      end
    else
      :Pas la bonne carte;
      :Aide;
   endif



repeat while (retanter ?) is (oui) not (non)
      :montré la carte a deviné;
         :Vous avez abandonné;
         :Strategie partie;
@endumll
-----
Dans ce 2éme challenge nous avons dû améliorer le jeu dans le fichier  "MainPlayConsole"


* TODO (A) demander au joueur s'il souhaite avoir de l'aide pour sa partie
** Création d'une variable d'aide du type Boolean, pour permettre au joueur d'avoir de l'aide
* TODO (A) demander au joueur avec quel jeu de cartes 32 ou 52 il souhaite jouer
** Utilisation avec un `read Line()`, nous avons demandé au Joeur de saisir un jeu de cartes de 32 ou 52 et nous avons bouclé ça avec une boucle Do While si la réponse du joueur n'est pas bonne
* TODO: (A) si l'aide est activée, alors dire si la carte proposée est plus grande ou plus petite
**Si la variable aide est en vrai, le jeu va afficher si la carte à trouver est plus grande ou plus petite à l'aide des simples mathématiques
* TODO (A) permettre au joueur de retenter une autre carte (sans relancer le jeu) ou d'abandonner la partie
** Grace a la boucle Do while nous avons peut relancer le code sans le re ecrire, cela nous permets d'optimiser le code, et sortir de la boucle si le Joueur decide d'abondonner
* TODO (A) Présenter à la fin la carte à deviner
**Pour Prestenter la carte a deviné nous avons utilisé un println avec dedans la funtion `${jeu.carteADeviner}`

== Challenge-3 : Rebattre les cartes
Nous avons cree une methode qui bat les carte a l'aide d'un `Shuffled` qui retourne une nouvelle liste avec les éléments de cette liste mélangés aléatoirement.
=== CarteTest

[source, kotlin]
----

 // Mehtode
   fun batLesCartes(list: List<Carte>): List<Carte> {
        return list.shuffled()
    }

 //Test
@Test
    fun testBatcarte() {
        val paquetDeuxCartes = Paquet(
            listOf(
                Carte(NomCarte.SIX, CouleurCarte.CARREAU),
                Carte(NomCarte.SEPT, CouleurCarte.COEUR),
                Carte(NomCarte.HUIT, CouleurCarte.COEUR),
                Carte(NomCarte.NEUF, CouleurCarte.CARREAU),
                Carte(NomCarte.DIX, CouleurCarte.PIQUE),
            )
        )

        val paquetMixed = paquetDeuxCartes.batLesCartes(paquetDeuxCartes.cartes)
        assertNotEquals(paquetDeuxCartes.cartes[0], paquetMixed[0])// test si la fonction batLesCarte fonctionne bien

    }

----
Et a l'aide de assertNotEquals nous vérifions si le premier element du paquetDeuxCartes n'est pas = au premier element du paquetMixed


== Challenge-4 : La stratégie du joueur
Création d'une fonction strategiepartie() convenable ou pas
L'utilisation de log2() permet de savoir si le nombre d'essais etait convenable ou invenable par rapport au paquet choisis.

Nous calculons ensuite le pourcentage de chance de trouver la bonne carte en fonction du nombre d'essais et du nombre de cartes dans le jeu.
Avec ce pourcentage de chance, nous pouvons dire si le joueur a de la chance ou non.

[source, kotlin]
----
 fun strategiePartie(abandonner: Boolean, nbEssai: Int): String {

        if (!abandonner) {
            if (avecAide) {
                val logEssai = log2(paquet.cartes.size.toDouble())
                if (nbEssai.toDouble() >= logEssai * 2) {
                    return "Le nombre d'essais n'est pas parfait: $nbEssai"
                } else if (nbEssai.toDouble() >= logEssai && nbEssai.toDouble() < logEssai * 2) {
                    return "La stratégie est bonne mais n'est pas parfaite, nombre d'essai: $nbEssai"
                } else if (nbEssai == logEssai.toInt()) {
                    return " La stratégie est parfaite, nombre d'essai: $nbEssai"
                } else if (nbEssai.toDouble() < logEssai) {
                    return "vous réfléchissez mieux qu'un robot, nombre d'essai: $nbEssai"
                }
            } else {
                val pourcentageChance = (nbEssai.toDouble() / paquet.cartes.size.toDouble()) * 100
                if (pourcentageChance <= 0.50) {
                    return "Vous avez de la chance, ${pourcentageChance.toInt()}% de chance, nomre d'essai: $nbEssai"
                } else {
                    return "Vous n'avez pas de chance, ${pourcentageChance.toInt()}% de chance, nomre d'essai: $nbEssai "
                }
            }
            return "Probleme, nombre d'essai :$nbEssai "
        } else {
            return "Vous avez abandonner"
        }


    }

----
